<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <RootNamespace>ServerSync</RootNamespace>
        <AssemblyName>ServerSync</AssemblyName>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <GamePath Condition="'$(GamePath)' == '' AND '$(OS)' == 'Unix' AND Exists('$(HOME)/Library/Application Support/Steam/steamapps/common/Valheim')">$(HOME)/Library/Application Support/Steam/steamapps/common/Valheim</GamePath>
        <GamePath Condition="'$(GamePath)' == '' AND '$(OS)' == 'Unix'">$(HOME)/.steam/steam/steamapps/common/Valheim</GamePath>
        <GamePath Condition="'$(GamePath)' == '' AND '$(OS)' == 'Windows_NT'">$([MSBuild]::GetRegistryValueFromView('HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 892970', 'InstallLocation', null, RegistryView.Registry64, RegistryView.Registry32))</GamePath>
        <SteamLibraryPath Condition="'$(OS)' == 'Windows_NT'">$([MSBuild]::GetRegistryValueFromView('HKEY_CURRENT_USER\SOFTWARE\Valve\Steam', 'SteamPath', null, RegistryView.Registry32))</SteamLibraryPath>
        <GamePath Condition="'$(GamePath)' == '' AND '$(SteamLibraryPath)' != ''">$(SteamLibraryPath)\steamapps\common\Valheim</GamePath>
        <GamePath Condition="'$(GamePath)' == '' AND '$(OS)' == 'Windows_NT' AND Exists('C:\Program Files\Steam\steamapps\common\Valheim')">C:\Program Files\Steam\steamapps\common\Valheim</GamePath>
        <GamePath Condition="'$(GamePath)' == '' AND '$(OS)' == 'Windows_NT'">C:\Program Files (x86)\Steam\steamapps\common\Valheim</GamePath>
        <ManagedPath Condition="'$(ManagedPath)' == '' AND '$(OS)' == 'Unix' AND Exists('$(GamePath)/Valheim.app/Contents/Resources/Data/Managed')">$(GamePath)/Valheim.app/Contents/Resources/Data/Managed</ManagedPath>
        <ManagedPath Condition="'$(ManagedPath)' == '' AND '$(OS)' == 'Unix'">$(GamePath)/valheim_Data/Managed</ManagedPath>
        <ManagedPath Condition="'$(ManagedPath)' == '' AND '$(OS)' == 'Windows_NT'">$(GamePath)/valheim_Data/Managed</ManagedPath>
        <BepInExCorePath Condition="'$(BepInExCorePath)' == ''">$(GamePath)/BepInEx/core</BepInExCorePath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="0Harmony">
            <HintPath>$(BepInExCorePath)/0Harmony.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="assembly_utils">
            <HintPath>$(ManagedPath)/assembly_utils.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="assembly_valheim">
            <HintPath>$(ManagedPath)/assembly_valheim.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="BepInEx">
            <HintPath>$(BepInExCorePath)/BepInEx.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Unity.TextMeshPro">
            <HintPath>$(ManagedPath)/Unity.TextMeshPro.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine">
            <HintPath>$(ManagedPath)/UnityEngine.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>$(ManagedPath)/UnityEngine.CoreModule.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.UI">
            <HintPath>$(ManagedPath)/UnityEngine.UI.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>
</Project>
